name: Continuous Integration - Other

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "macOS",
            os: macos-latest
          }
        - {
            name: "Linux",
            os: ubuntu-latest
          }

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        if [[ "${{ runner.os }}" == 'macOS' ]]; then
          make mac
        elif [[ "${{ runner.os }}" == 'Linux' ]]; then
          sudo apt-get install mesa-common-dev
          make linux
        fi

    - name: Test Files Presence
      run: |
        ls -lR .
        # TODO

    - name: Prepare Package
      run: |
        # Delete unwanted files
        rm -r Build/Setup

    - name: Upload Package
      uses: actions/upload-artifact@v1
      with:
        path: Build
        name: "vs_${{matrix.config.name }}"
